# Regenerates the slides/data/*.js files that deck.html renders figures from.
#
#     julia slides/data/generate.jl
#
# The deck loads these with <script src="data/....js"> instead of fetch(),
# so the slides work when opened straight from file:// — no web server needed.
# Swap the hardcoded numbers below for whatever collection you like
# (e.g. re-run the benchmark suite and read benchmark/results/data.jls).

datadir = @__DIR__

jsnum(x::Real) = isinteger(x) ? string(Int(x)) : string(x)
jslist(xs) = "[" * join(jsnum.(xs), ", ") * "]"
jsstrlist(xs) = "[" * join("\"" .* xs .* "\"", ", ") * "]"

function write_js(file, key, body)
    open(joinpath(datadir, file), "w") do io
        println(io, "// Generated by slides/data/generate.jl — do not edit by hand.")
        println(io, "window.DECK_DATA = window.DECK_DATA || {};")
        println(io, "window.DECK_DATA.", key, " = ", body, ";")
    end
    return @info "wrote $file"
end

# ---- per-op bar chart (deck slide: figure / bar chart) ----------------------
ops = [
    ("*  (multiply)", 17.7, 22.7),
    ("/  (divide)", 22.7, 25.8),
    ("exp", 26.5, 24.3),
    ("sqrt", 13.8, 14.7),
    ("sin", 29.5, 31.7),
]

rows = join(
    ("  { \"op\": \"$op\", \"vals\": $(jslist((a, b))) }" for (op, a, b) in ops),
    ",\n"
)

write_js(
    "ops.js", "ops", """
    {
      "series": $(jsstrlist(["HyperDual{8,8}", "nested Dual 8×8 (patched FD)"])),
      "colors": $(jsstrlist(["hh", "fd8"])),
      "unit": "ns",
      "rows": [
    $rows
      ]
    }"""
)

# ---- finite-difference error vs step size (computed live) -------------------
# |fd(f, x, h) - f'(x)| for f(x) = x*sin(x^2) at x = 2 — the classic V curve.
let
    f(x) = x * sin(x * x)
    fd(f, x, h) = (f(x + h) - f(x)) / h
    exact = sin(4.0) + 8cos(4.0)
    hs = [10.0^e for e in range(-16, 0; length = 65)]
    errs = [max(abs(fd(f, 2.0, h) - exact) / abs(exact), 1.0e-17) for h in hs]

    write_js(
        "fderr.js", "fderr", """
        {
          "fn": "f(x) = x sin(x²) at x = 2, relative error",
          "h": $(jslist(hs)),
          "err": $(jslist(errs))
        }"""
    )
end

# ---- throughput per flop: HyperDual{n,n} vs nested Dual multiply ------------
# From benchmark/mul_scaling.jl (benchmark/results/mulscale-*.tsv). Both layouts
# carry (1+n)^2 floats and their product rules do the same 7n^2 + 6n + 1 flops,
# so GFLOP/s differences are pure data layout / codegen.
let
    ns = 1:12
    flops = [7n^2 + 6n + 1 for n in ns]
    # ns per multiply, BenchmarkTools minimum, single core.
    # "simd" is HyperDual with explicit SIMD.Vec arithmetic (simd = true).
    m4_hh = [0.93, 0.92, 1.99, 2.51, 5.21, 6.39, 14.42, 17.36, 29.11, 41.88, 40.42, 54.04]
    m4_simd = [0.93, 1.04, 2.04, 2.66, 4.99, 6.57, 14.36, 21.67, 32.69, 34.37, 43.24, 49.8]
    m4_fd = [1.08, 1.36, 3.07, 4.32, 7.45, 9.38, 16.64, 25.43, 31.62, 36.46, 47.72, 54.62]
    zen4_hh = [1.25, 9.4, 17.36, 9.02, 18.12, 20.03, 22.04, 17.02, 38.29, 31.37, 55.1, 43.53]
    zen4_simd = [1.25, 2.12, 4.72, 5.34, 11.22, 12.44, 17.73, 16.6, 25.95, 28.91, 39.08, 40.1]
    zen4_fd = [1.21, 9.46, 17.87, 10.36, 16.04, 23.96, 34.01, 53.55, 72.73, 63.46, 72.19, 92.97]
    gf(ts) = [round(flops[i] / ts[i]; digits = 2) for i in eachindex(ts)]
    series(hh, simd, fd) = """
    [
          { "name": "HyperDual{n,n}",         "color": "hh",   "gflops": $(jslist(gf(hh))) },
          { "name": "HyperDual + SIMD.Vec",   "color": "simd", "gflops": $(jslist(gf(simd))) },
          { "name": "nested Dual{Dual}",      "color": "fd8",  "gflops": $(jslist(gf(fd))) }
        ]"""

    write_js(
        "mulflops.js", "mulflops", """
        {
          "n": $(jslist(collect(ns))),
          "machines": [
            { "name": "Apple M4 — 128-bit NEON", "series": $(series(m4_hh, m4_simd, m4_fd)) },
            { "name": "AMD Zen 4 — AVX-512",     "series": $(series(zen4_hh, zen4_simd, zen4_fd)) }
          ]
        }"""
    )
end

# ---- scaling line chart (deck slide: figure from a data file) ---------------
# ackley full Hessian, benchmark/results/summary.md (arrowlake-s), times in µs.
n = [2, 4, 8, 16, 32, 64, 128, 256]
fd = [0.0607, 0.2294, 0.8891, 6.12, 41.38, 293.23, 2090.0, 16190.0]
hh = [0.0289, 0.0598, 0.2284, 1.6, 8.13, 49.6, 344.03, 2570.0]

write_js(
    "scaling.js", "scaling", """
    {
      "title": "ackley dense Hessian",
      "n": $(jslist(n)),
      "unit": "us",
      "series": [
        { "name": "ForwardDiff",   "color": "fd8", "us": $(jslist(fd)) },
        { "name": "HyperHessians", "color": "hh",  "us": $(jslist(hh)) }
      ]
    }"""
)

# ---- threaded Hessian scaling (deck slide: threaded Hessians) ---------------
# ackley n = 512, Chunk{8}, Apple M4 Pro, julia -t N, BenchmarkTools minimum
# in ms; serial = HessianConfig, threaded = ThreadedHessianConfig (ntasks = N).
# Measured up to 14 threads; shown up to the 8 performance cores (beyond:
# 10.93, 10.04, 9.7 ms at 10, 12, 14 — flat once the small cores join).
threads = [1, 2, 4, 6, 8]
tms = [78.82, 40.61, 19.77, 15.62, 10.49]

write_js(
    "threads.js", "threads", """
    {
      "func": "ackley", "n": 512, "chunk": 8,
      "serial_ms": 83.69,
      "threads": $(jslist(threads)),
      "ms": $(jslist(tms))
    }"""
)
