# Regenerates the slides/data/*.js files that deck.html renders figures from.
#
#     julia slides/data/generate.jl
#
# The deck loads these with <script src="data/....js"> instead of fetch(),
# so the slides work when opened straight from file:// — no web server needed.
# Swap the hardcoded numbers below for whatever collection you like
# (e.g. re-run the benchmark suite and read benchmark/results/data.jls).

datadir = @__DIR__

jsnum(x::Real) = isinteger(x) ? string(Int(x)) : string(x)
jslist(xs) = "[" * join(jsnum.(xs), ", ") * "]"
jsstrlist(xs) = "[" * join("\"" .* xs .* "\"", ", ") * "]"

function write_js(file, key, body)
    open(joinpath(datadir, file), "w") do io
        println(io, "// Generated by slides/data/generate.jl — do not edit by hand.")
        println(io, "window.DECK_DATA = window.DECK_DATA || {};")
        println(io, "window.DECK_DATA.", key, " = ", body, ";")
    end
    return @info "wrote $file"
end

# ---- per-op bar chart (deck slide: figure / bar chart) ----------------------
ops = [
    ("*  (multiply)", 17.7, 22.7),
    ("/  (divide)", 22.7, 25.8),
    ("exp", 26.5, 24.3),
    ("sqrt", 13.8, 14.7),
    ("sin", 29.5, 31.7),
]

rows = join(
    ("  { \"op\": \"$op\", \"vals\": $(jslist((a, b))) }" for (op, a, b) in ops),
    ",\n"
)

write_js(
    "ops.js", "ops", """
    {
      "series": $(jsstrlist(["HyperDual{8,8}", "nested Dual 8×8 (patched FD)"])),
      "colors": $(jsstrlist(["hh", "fd8"])),
      "unit": "ns",
      "rows": [
    $rows
      ]
    }"""
)

# ---- finite-difference error vs step size (computed live) -------------------
# |fd(f, x, h) - f'(x)| for f(x) = x*sin(x^2) at x = 2 — the classic V curve.
let
    f(x) = x * sin(x * x)
    fd(f, x, h) = (f(x + h) - f(x)) / h
    exact = sin(4.0) + 8cos(4.0)
    hs = [10.0^e for e in range(-16, 0; length = 65)]
    errs = [max(abs(fd(f, 2.0, h) - exact) / abs(exact), 1.0e-17) for h in hs]

    write_js(
        "fderr.js", "fderr", """
        {
          "fn": "f(x) = x sin(x²) at x = 2, relative error",
          "h": $(jslist(hs)),
          "err": $(jslist(errs))
        }"""
    )
end

# ---- scaling line chart (deck slide: figure from a data file) ---------------
# ackley full Hessian, benchmark/results/summary.md (arrowlake-s), times in µs.
n = [2, 4, 8, 16, 32, 64, 128, 256]
fd = [0.0607, 0.2294, 0.8891, 6.12, 41.38, 293.23, 2090.0, 16190.0]
hh = [0.0289, 0.0598, 0.2284, 1.6, 8.13, 49.6, 344.03, 2570.0]

write_js(
    "scaling.js", "scaling", """
    {
      "title": "ackley dense Hessian",
      "n": $(jslist(n)),
      "unit": "us",
      "series": [
        { "name": "ForwardDiff",   "color": "fd8", "us": $(jslist(fd)) },
        { "name": "HyperHessians", "color": "hh",  "us": $(jslist(hh)) }
      ]
    }"""
)
